import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CardsList from '@/components/Products/CardList'
import NavBar from '@/components/Navigation/NavBar'
import ShoppingCart from '@/components/Cart/ShoppingCart'
import CartIcon from '@/components/Cart/CartIcon'
import AddToCartButton from '@/components/add_button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
        <h1>Pet Land</h1>
        </header>
        <section>
          {/* <CartIcon/> */}
        <NavBar/>
          {/* <CardsList/> */}
          <ShoppingCart/>
          <AddToCartButton/>
      </section>
      </main>
    </>
  )
}
